app/ChatSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='chat_app:list_threads')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('messages/', include('chat_app.urls')),
]

app/chat_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from .views import ThreadView, ThreadsView


app_name = 'chat_app'
redirect_url = '/accounts/login'

urlpatterns = [
    path('', login_required(ThreadsView.as_view()), name='list_threads'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', login_required(ThreadView.as_view()), name='chat_thread'),
]

app/chat_app/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(receiver=user) | Q(sender=user)
        qlookup2 = Q(receiver=user) & Q(sender=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2)
        return qs

    def get_or_new(self, user1, username2):
        username1 = user1.username
        # User can't have a chat with itself
        if username1 == username2:
            return None, False
        # Both queues are aming to find a thread combination of two users
        qlookup1 = Q(receiver__username=username1) & Q(sender__username=username2)
        qlookup2 = Q(receiver__username=username2) & Q(sender__username=username1)
        qs = self.get_queryset().filter(qlookup1 | qlookup2)
        # If only one result found, return it
        if qs.count() == 1:
            return qs.first(), False
        # If more than one result found, return latest one
        elif qs.count() > 1:
            return qs.order_by('timestamp').last(), False
        else:
            # If none found then create one
            user_class = user1.__class__
            user2 = user_class.objects.get(username=username2)
            # User can't send messages to himself
            if user1 != user2:
                obj = self.model(
                    receiver=user2,
                    sender=user1
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_receiver')
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_sender')
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    def __str__(self):
        return f'Sent by {self.sender} to {self.receiver}'


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

app/chat_app/forms.py
from django import forms
from .models import Thread


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

app/chat_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.views.generic.edit import FormMixin
from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class ThreadsView(LoginRequiredMixin, ListView):
    template_name = 'chat_app/dialogs.html'
    context_object_name = 'threads'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat_app/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)

        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

app/chat_app/templates/chat_app/dialogs.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'chat_app/navigation.html' %}
{% endblock %}
{% block content %}
    {% for thread in threads %}
    <div class="card mt-2">
        <div class="card-body">
            <h5 class="card-title">{% if user != thread.receiver %}{{ thread.receiver }}{% else %}{{ thread.sender }}{% endif %}</h5>
            <a href="{% if user != thread.receiver %}
                         {% url 'chat_app:chat_thread' username=thread.receiver %}
                     {% else %}
                         {% url 'chat_app:chat_thread' username=thread.sender %}
                     {% endif %}"
               class="btn btn-primary">Start chat</a>
        </div>
     </div>
    {% endfor %}
{% endblock %}

app/chat_app/templates/chat_app/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav">
            <a class="navbar-brand" href="#">{{ request.user.username }}</a>
            <a class="nav-item nav-link" href="{% url 'chat_app:list_threads' %}">My Chats</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
</nav>

app/chat_app/templates/chat_app/thread.html
{% extends "base.html" %}
{% block navigation %}
    {% include 'chat_app/navigation.html' %}
{% endblock %}
{% block content %}
    <h3>Chat with {% if user != object.receiver %}{{ object.receiver }}{% else %}{{ object.sender }}{% endif %}</h3>
    <div id="chat-div" class="container" style=" height:600px; overflow-y: scroll; overflow-x: hidden">
        <ul id='chat-items' class="list-group">
        {% for chat in object.chatmessage_set.all %}
            <li class="list-group-item mw-300 ">
                <div class="d-flex justify-content-between">
                    <h5 class="mb-1">{{ chat.user }}:</h5>
                    <small>{{ chat.timestamp }}</small>
                </div>
                <p class="mb-1">{{ chat.message }}</p>
            </li>
        {% endfor %}
        </ul>
    </div>
    <form id='form' method='POST'> {% csrf_token %}
        {{form.as_p }}
        <input type='submit' class='btn btn-primary' value="Send">
    </form>

{% endblock %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>
    <script>
        // websocket scripts
        var loc = window.location
        var form_data = $("#form")
        var ws_prefix = (loc.protocol == 'https:') ? 'wss://':'ws://'
        var endpoint = ws_prefix + loc.host + loc.pathname
        var socket = new ReconnectingWebSocket(endpoint)
        var chat_items = $('#chat-items')
        var chat_div = $('#chat-div')

        socket.onmessage = function (e) {
            console.log('message', e)
            var new_message = JSON.parse(e.data)
            html_string = '<li class="list-group-item">' +
                '<div class="d-flex justify-content-between">' +
                '<h5 class="mb-1">' + new_message.user + ':</h5>' +
                '<small>' + new_message.time + '</small></div>' +
                '<p class="mb-1">' + new_message.msg + '</p></li>'
            chat_items.append(html_string)
            chat_div.scrollTop = chat_div.scrollHeight;
        }

        socket.onopen = function (e) {
            console.log('open', e)
            form_data.submit(function (event) {
                event.preventDefault()
                data = $('#id_message').val()
                msg = {'msg': data,}
                socket.send(JSON.stringify(msg))
                form_data[0].reset()
            })
        }

        socket.onerror = function (e) {
            console.log('error', e)
        }

        socket.onclose = function (e) {
            console.log('close', e)
        }
    </script>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>ChatSite</title>
        {% include 'css.html' %}
    </head>
    <body>
        <div class='container'>
        {% block navigation %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        </div>
        {% include 'js.html' %}
        {% block script %}
        {% endblock %}
    </body>
</html>

app/templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

app/templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>